name: mlspock
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python >= 3.9
  - pip
  - numpy=1.26.3
  - pytorch=1.13.0
  - cuda-toolkit=11.6
  - torchvision=0.14.0
  - tmux
  - pip:
    - click==8.1.7
    - h5py==3.10.0
    - matplotlib==3.8.2
    - pandas==2.2.0
    - plotly==5.19.0
    - plotly-express==0.4.1
    - scikit-learn==1.3.2
    - scipy==1.11.4
    - seaborn==0.13.2